/*********************************************************************************
 *                                                                               *
 * WARNING: File automatically generated by DMXmlJson. DON'T CHANGE IT manually! *
 *                                                                               *
 *********************************************************************************/

package bz.davide.javabindlibcomparison.model;


public class XmlJsonUnmarshaller_Helper extends bz.davide.dmxmljson.unmarshalling.Unmarshaller
{
   protected XmlJsonUnmarshaller_Helper()
   {
      this.emptyObjectCheck.put("bz.davide.javabindlibcomparison.model.Invoice", new bz.davide.dmxmljson.unmarshalling.EmptyFieldChecker<bz.davide.javabindlibcomparison.model.Invoice>() {
         @Override public void check(bz.davide.javabindlibcomparison.model.Invoice  ret){
            // number
            if (ret.number != null)
               throw new RuntimeException("The constructor initialized the field bz.davide.javabindlibcomparison.model.Invoice.number");
         }
      });
      this.putInstanceFactory("bz.davide.javabindlibcomparison.model.Invoice", new bz.davide.dmxmljson.unmarshalling.InstanceFactory() {
         @Override public Object newInstance() throws Exception {
            bz.davide.javabindlibcomparison.model.Invoice ret = new bz.davide.javabindlibcomparison.model.Invoice();
            emptyObjectCheck.get("bz.davide.javabindlibcomparison.model.Invoice").check(ret);
            return ret;
         }
      });

      this.putClassUnmarshaller("bz.davide.javabindlibcomparison.model.Invoice", new bz.davide.dmxmljson.unmarshalling.ClassUnmarshaller() {
         @Override public void unmarshall(bz.davide.dmxmljson.unmarshalling.Structure structure, Object obj, java.util.HashMap<String, Object> identities) throws Exception {
            structure.open();
            String id = structure.getId();
            if (id != null)
               identities.put(id, obj);
            bz.davide.dmxmljson.unmarshalling.Value value;
            // number
            if ((value = structure.property("number")) != null)
               if (value.isNull())
                  ((bz.davide.javabindlibcomparison.model.Invoice)obj).number = null;
               else
               {
                  ((bz.davide.javabindlibcomparison.model.Invoice)obj).number = value.string();
               }
            structure.close();
         }
      });

   }
}
